version: '3'

x-logging: &default-logging
  options:
    max-size: '100m'
    max-file: '5'
    tag: '{{.ImageName}}|{{.Name}}'
  driver: json-file

services:
  db:
    container_name: performance-tracker-server_db-1
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - net
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    logging: *default-logging

  minio:
    container_name: performance-tracker-server_minio-1
    image: 'minio/minio:latest'
    environment:
      MINIO_DOMAIN: localhost
      MINIO_ROOT_USER: 'minioroot'
      MINIO_ROOT_PASSWORD: 'minioroot'
    command: minio server /data/minio --console-address ":9090"
    networks:
      - net
    ports:
      - target: 9000
        published: 9002
        protocol: tcp
        mode: host
      - target: 9090
        published: 9091
        protocol: tcp
        mode: host
    volumes:
      - 'minio_data:/data/minio'
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    logging: *default-logging

volumes:
  db_data:
  minio_data:
    driver: local

networks:
  net:
