import { AthleteIntakeTable } from './athlete-intake-table.interface';
import { AthleteProfileMetricsTable } from './athlete-profile-metrics-table.interface';
import { AthleteRacesTable } from './athlete-races-table.interface';
import { HistoricalRaceResultsTable } from './historical-race-results-table.interface';
import { PeriodizationPlansTable } from './periodization-plans-table.interface';
import { RaceEventsTable } from './race-events-table.interface';
import { RacePredictionsTable } from './race-predictions-table.interface';
import { RacePlansTable } from './race-plans-table.interface';
import { WeatherForecastsTable } from './weather-forecasts-table.interface';
import { AthletePrivacySettingsTable } from './athlete-privacy-settings-table.interface';
import { SleepBaselinesTable } from './sleep-baselines-table.interface';
import { CardioCategoriesTable } from './cardio-categories-table.interface';
import { CardioMetricsTable } from './cardio-metrics-table.interface';
import { CardioStepGroupItemsTable } from './cardio-step-group-items-table.interface';
import { CardioStepGroupsTable } from './cardio-step-groups-table.interface';
import { CardioStepsTable } from './cardio-steps-table.interface';
import { CoachAssignedWorkoutsTable } from './coach-assigned-workouts-table.interface';
import { CoachAthleteLabelsTable } from './coach-athlete-labels-table.interface';
import { CoachAthleteRelationshipsTable } from './coach-athlete-relationships-table.interface';
import { CoachScheduledPromptsTable } from './coach-scheduled-prompts-table.interface';
import { CoachingMessagesTable } from './coaching-messages-table.interface';
import { DailyHealthMetricsTable } from './daily-health-metrics-table.interface';
import { DailyTrainingLoadsTable } from './daily-training-loads-table.interface';
import { DataExportJobsTable } from './data-export-jobs-table.interface';
import { DataImportJobsTable } from './data-import-jobs-table.interface';
import { EquipmentTable } from './equipment-table.interface';
import { ExecutionWeatherTable } from './execution-weather-table.interface';
import { ExerciseChainMembersTable, ExerciseChainsTable } from './exercise-chains-table.interface';
import { ExerciseEquipmentTable } from './exercise-equipment-table.interface';
import { ExerciseImagesTable } from './exercise-images-table.interface';
import { ExerciseInstanceGroupItemsTable } from './exercise-instance-group-items-table.interface';
import { ExerciseInstanceGroupsTable } from './exercise-instance-groups-table.interface';
import { ExerciseInstancesTable } from './exercise-instances-table.interface';
import { ExerciseMuscleGroupsTable } from './exercise-muscle-groups-table.interface';
import { ExercisesTable } from './exercises-table.interface';
import { FitnessFatigueDailyTable } from './fitness-fatigue-daily-table.interface';
import { FitnessMetricsTable } from './fitness-metrics-table.interface';
import { HrvBaselineDailyTable } from './hrv-baseline-daily-table.interface';
import { LoadModelParametersTable } from './load-model-parameters-table.interface';
import { IllnessLogsTable } from './illness-logs-table.interface';
import { QuickWellnessCheckinsTable } from './quick-wellness-checkins-table.interface';
import { RpeTssTrackingTable } from './rpe-tss-tracking-table.interface';
import { MultiStreamLoadDailyTable } from './multi-stream-load-daily-table.interface';
import { MuscleGroupsTable } from './muscle-groups-table.interface';
import { NotificationsTable } from './notifications-table.interface';
import { OAuthStatesTable } from './oauth-states-table.interface';
import { PainLogsTable } from './pain-logs-table.interface';
import { PersonalRecordHistoryTable } from './personal-record-history-table.interface';
import { PersonalRecordsTable } from './personal-records-table.interface';
import { RecoveryJournalEntriesTable } from './recovery-journal-entries-table.interface';
import { RefreshTokensTable } from './refresh-tokens-table.interface';
import { RouteMarkersTable } from './route-markers-table.interface';
import { SetCompletionsTable } from './set-completions-table.interface';
import { SleepLogsTable } from './sleep-logs-table.interface';
import { TrainingStressScoresTable } from './training-stress-scores-table.interface';
import { UserIntegrationsTable } from './user-integrations-table.interface';
import { UserSettingsTable } from './user-settings-table.interface';
import { UsersTable } from './users-table.interface';
import { WearableProviderConnectionsTable } from './wearable-provider-connections-table.interface';
import { WearableProviderPrioritiesTable } from './wearable-provider-priorities-table.interface';
import { WorkoutExecutionsTable } from './workout-executions-table.interface';
import { WorkoutFileImportsTable } from './workout-file-imports-table.interface';
import { WorkoutItemsTable } from './workout-items-table.interface';
import { WorkoutPlanItemsTable } from './workout-plan-items-table.interface';
import { WorkoutPlansTable } from './workout-plans-table.interface';
import { WorkoutRoutesTable } from './workout-routes-table.interface';
import { WorkoutSchedulesTable } from './workout-schedules-table.interface';
import { WorkoutsTable } from './workouts-table.interface';

export interface Database {
  users: UsersTable;
  refresh_tokens: RefreshTokensTable;
  exercises: ExercisesTable;
  equipment: EquipmentTable;
  exercise_equipment: ExerciseEquipmentTable;
  muscle_groups: MuscleGroupsTable;
  exercise_muscle_groups: ExerciseMuscleGroupsTable;
  exercise_images: ExerciseImagesTable;
  exercise_instances: ExerciseInstancesTable;
  exercise_instance_groups: ExerciseInstanceGroupsTable;
  exercise_instance_group_items: ExerciseInstanceGroupItemsTable;
  workouts: WorkoutsTable;
  workout_items: WorkoutItemsTable;
  workout_schedules: WorkoutSchedulesTable;
  workout_executions: WorkoutExecutionsTable;
  set_completions: SetCompletionsTable;
  cardio_categories: CardioCategoriesTable;
  cardio_metrics: CardioMetricsTable;
  cardio_steps: CardioStepsTable;
  cardio_step_groups: CardioStepGroupsTable;
  cardio_step_group_items: CardioStepGroupItemsTable;
  workout_routes: WorkoutRoutesTable;
  route_markers: RouteMarkersTable;
  user_integrations: UserIntegrationsTable;
  user_settings: UserSettingsTable;
  workout_file_imports: WorkoutFileImportsTable;
  workout_plans: WorkoutPlansTable;
  workout_plan_items: WorkoutPlanItemsTable;
  daily_training_loads: DailyTrainingLoadsTable;
  personal_records: PersonalRecordsTable;
  personal_record_history: PersonalRecordHistoryTable;
  execution_weather: ExecutionWeatherTable;
  sleep_logs: SleepLogsTable;
  oauth_states: OAuthStatesTable;
  fitness_metrics: FitnessMetricsTable;
  training_stress_scores: TrainingStressScoresTable;
  fitness_fatigue_daily: FitnessFatigueDailyTable;
  exercise_chains: ExerciseChainsTable;
  exercise_chain_members: ExerciseChainMembersTable;
  pain_logs: PainLogsTable;
  wearable_provider_connections: WearableProviderConnectionsTable;
  wearable_provider_priorities: WearableProviderPrioritiesTable;
  daily_health_metrics: DailyHealthMetricsTable;
  data_import_jobs: DataImportJobsTable;
  data_export_jobs: DataExportJobsTable;
  coach_athlete_relationships: CoachAthleteRelationshipsTable;
  athlete_privacy_settings: AthletePrivacySettingsTable;
  athlete_intake: AthleteIntakeTable;
  coach_assigned_workouts: CoachAssignedWorkoutsTable;
  coach_athlete_labels: CoachAthleteLabelsTable;
  coaching_messages: CoachingMessagesTable;
  notifications: NotificationsTable;
  coach_scheduled_prompts: CoachScheduledPromptsTable;

  // Multi-stream load modeling
  multi_stream_load_daily: MultiStreamLoadDailyTable;
  recovery_journal_entries: RecoveryJournalEntriesTable;
  hrv_baseline_daily: HrvBaselineDailyTable;
  load_model_parameters: LoadModelParametersTable;
  rpe_tss_tracking: RpeTssTrackingTable;
  quick_wellness_checkins: QuickWellnessCheckinsTable;
  illness_logs: IllnessLogsTable;

  // Race Calendar
  race_events: RaceEventsTable;
  athlete_races: AthleteRacesTable;
  periodization_plans: PeriodizationPlansTable;

  // Race Predictions
  athlete_profile_metrics: AthleteProfileMetricsTable;
  race_predictions: RacePredictionsTable;
  historical_race_results: HistoricalRaceResultsTable;
  race_plans: RacePlansTable;
  weather_forecasts: WeatherForecastsTable;

  // Sleep baselines for enhanced sleep scoring
  sleep_baselines: SleepBaselinesTable;
}
